POST http://localhost:3000/cliente-auto
content-type: application/json

{
    "precio_compra": 400,
    "clienteId": "58aaab6b-fe1e-4554-b6e0-91624e85d07a",
    "autoId": "658147b1-91dd-4728-aba2-61395440ab87"
}